name: Build Packages

on: [push, pull_request]

jobs:
  build-rpm-fedora:
    name: linux build fedora rpm
    runs-on: ubuntu-20.04
    container: fedora:33
    timeout-minutes: 30

    strategy:
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install dependencies
      run: |
        dnf install -y rpm-build dnf-plugins-core
        sed -e 's/@VERSION@/0.0.1/' rhel/openvswitch-fedora.spec.in \
            > /tmp/ovs.spec
        dnf builddep -y /tmp/ovs.spec
        rm -f /tmp/ovs.spec

    - name: configure
      run:  ./boot.sh && ./configure
    - name: build rpm
      run: make rpm-fedora

    - name: upload rpm packages
      uses: actions/upload-artifact@v2
      with:
        name: rpm-packages
        path: |
          rpm/rpmbuild/SRPMS/*.rpm
          rpm/rpmbuild/RPMS/*/*.rpm

    - name: upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: logs-rpm-fedora
        path: config.log
